-- ============================================================================
-- Student Toolkit — Phase 1 data model
--
-- Student leaders are modeled in their OWN table, fully decoupled from
-- circle_leaders (students don't use CCB groups/circles, and their auth must
-- never touch circle/team sessions). This mirrors the leader-session +
-- OTP + message-center shapes used by the Circle/Teams toolkits, but every
-- table FKs to student_leaders and the toolkit uses its own session cookie.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. student_leaders — the people who can sign into the Student Toolkit
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS student_leaders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  campus TEXT,
  -- 'active' | 'archived' (lowercased). Archived leaders can't sign in.
  status TEXT NOT NULL DEFAULT 'active',
  -- Per-leader kill switch, independent of status (mirrors
  -- circle_summary_access_enabled). FALSE blocks toolkit access.
  toolkit_access_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS student_leaders_email_idx ON student_leaders (LOWER(email));
CREATE INDEX IF NOT EXISTS student_leaders_phone_idx ON student_leaders (phone);

ALTER TABLE student_leaders ENABLE ROW LEVEL SECURITY;

-- Internal RADIUS admins (authenticated) can read the roster; all writes and
-- all public toolkit auth go through the server-side service role.
DROP POLICY IF EXISTS "Authenticated read student_leaders" ON student_leaders;
CREATE POLICY "Authenticated read student_leaders"
  ON student_leaders FOR SELECT TO authenticated USING (true);

-- ----------------------------------------------------------------------------
-- 2. student_sessions — opaque HTTP-only cookie sessions (service-role only)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS student_sessions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  student_leader_id BIGINT NOT NULL REFERENCES student_leaders(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  user_agent TEXT,
  ip INET,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  revoked_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS student_sessions_leader_idx
  ON student_sessions (student_leader_id, created_at DESC);

CREATE INDEX IF NOT EXISTS student_sessions_active_idx
  ON student_sessions (student_leader_id, last_seen_at DESC)
  WHERE revoked_at IS NULL;

ALTER TABLE student_sessions ENABLE ROW LEVEL SECURITY;
-- No policies: read/written exclusively by the service role in auth routes.

-- ----------------------------------------------------------------------------
-- 3. student_otp_codes — short-lived 6-digit sign-in codes
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS student_otp_codes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  student_leader_id BIGINT REFERENCES student_leaders(id) ON DELETE CASCADE,
  code_hash TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  consumed_at TIMESTAMPTZ,
  request_ip TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS student_otp_codes_leader_idx
  ON student_otp_codes (student_leader_id, created_at DESC);

CREATE INDEX IF NOT EXISTS student_otp_codes_active_idx
  ON student_otp_codes (expires_at)
  WHERE consumed_at IS NULL;

ALTER TABLE student_otp_codes ENABLE ROW LEVEL SECURITY;
-- No policies: service-role only (matches leader_otp_codes write path).

-- ----------------------------------------------------------------------------
-- 4. student_messages — the Student Toolkit's own message stream
--    (separate from circle_summary_messages so students get their own
--     announcements, independent of circle/team messages)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS student_messages (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  header TEXT NOT NULL,
  body_html TEXT NOT NULL DEFAULT '',
  url TEXT,
  url_label TEXT,
  campus_filter TEXT[] NOT NULL DEFAULT '{}',
  start_date DATE,
  end_date DATE,
  priority INT NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS student_messages_window_idx
  ON student_messages (start_date, end_date, priority DESC);

ALTER TABLE student_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated read student_messages" ON student_messages;
CREATE POLICY "Authenticated read student_messages"
  ON student_messages FOR SELECT TO authenticated USING (true);
