-- ============================================================================
-- Student Leader Toolkit — roster, attendance, content, and push
--
-- Supersedes the deferred half of 20260622000000_student_toolkit.sql. That
-- migration shipped student_leaders/sessions/otp_codes and then stalled: the
-- spec assumed students had no persistent CCB group, so there was no source for
-- "which students belong to which leader" and the roster was cut. Students DO
-- check into CCB groups weekly; staff map those groups per campus and term in
-- student_ministry_groups below, and the nightly sync fills the rest.
--
-- Everything here is service-role only (RLS on, no browser policies), matching
-- the Circle and Teams toolkits. Nothing in this file alters a Radius table's
-- existing rows.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. student_ministry_groups — the CCB group map staff fill in
--
-- One row per (campus, term, kind). `kind` separates the two attendance
-- questions a leader asks: did they come to *their circle*, and did they come
-- to the *movement* (the main student gathering). Until a campus has rows here
-- the toolkit still works — the roster just reports attendance as unconnected.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS student_ministry_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus TEXT NOT NULL,
  -- Semester slug, e.g. '2026-fall'. Student groups are rebuilt every term.
  term TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('circle', 'movement')),
  ccb_group_id TEXT NOT NULL,
  -- Human label for the admin screen ("Denton 7th Grade Guys").
  label TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  last_synced_at TIMESTAMPTZ,
  last_sync_error TEXT,
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- A campus can have several circle groups per term (one per grade), but the
-- same CCB group must not be registered twice for the same purpose.
CREATE UNIQUE INDEX IF NOT EXISTS student_ministry_groups_unique_idx
  ON student_ministry_groups (campus, term, kind, ccb_group_id);

CREATE INDEX IF NOT EXISTS student_ministry_groups_active_idx
  ON student_ministry_groups (term, active, campus);

ALTER TABLE student_ministry_groups ENABLE ROW LEVEL SECURITY;
-- No policies: the admin screen reads and writes through a server route on the
-- service role, like every other toolkit table.

-- ----------------------------------------------------------------------------
-- 2. student_directory_cache — students pulled from the mapped CCB groups
--
-- The pool a leader picks their roster from. Deliberately narrow: name,
-- birthday, grade. No phone, no email, no address — these are minors and the
-- toolkit never surfaces contact info (leaders reach students via GroupMe).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS student_directory_cache (
  term TEXT NOT NULL,
  ccb_individual_id TEXT NOT NULL,
  campus TEXT,
  -- The group we last saw them in. A student can be in both the circle and the
  -- movement group, so membership is tracked by the flags below rather than by
  -- this column, which is only ever last-writer-wins.
  ccb_group_id TEXT,
  first_name TEXT,
  last_name TEXT,
  full_name TEXT,
  birthday TEXT,
  grade TEXT,
  -- Which of the campus's mapped groups currently list this student. A student
  -- in the movement group but NOT the circle group is exactly the person a
  -- leader most wants on their roster, so the candidate picker searches the
  -- union of both rather than filtering on either.
  in_circle_group BOOLEAN NOT NULL DEFAULT FALSE,
  in_movement_group BOOLEAN NOT NULL DEFAULT FALSE,
  -- FALSE once CCB stops listing them in every mapped group (soft delete, so a
  -- leader's roster row survives a mid-semester group edit and the leader can
  -- still see that the student dropped off).
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  last_seen_in_group_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (term, ccb_individual_id)
);

CREATE INDEX IF NOT EXISTS student_directory_cache_campus_idx
  ON student_directory_cache (campus, term, is_active);

CREATE INDEX IF NOT EXISTS student_directory_cache_name_idx
  ON student_directory_cache (LOWER(full_name));

ALTER TABLE student_directory_cache ENABLE ROW LEVEL SECURITY;
-- No policies: read/written exclusively by the service role.

-- ----------------------------------------------------------------------------
-- 3. student_attendance — one row per student per occurrence they attended
--
-- Storing per-week rows rather than a single last-attended date costs almost
-- nothing and is what a "4 of the last 8 weeks" consistency read would need
-- later. "Last attended" is just MAX(occurrence) per kind.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS student_attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ccb_individual_id TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('circle', 'movement')),
  occurrence DATE NOT NULL,
  ccb_group_id TEXT NOT NULL,
  ccb_event_id TEXT,
  term TEXT NOT NULL,
  synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS student_attendance_unique_idx
  ON student_attendance (ccb_individual_id, kind, occurrence);

-- Drives the roster read: latest occurrence per student per kind.
CREATE INDEX IF NOT EXISTS student_attendance_lookup_idx
  ON student_attendance (ccb_individual_id, kind, occurrence DESC);

ALTER TABLE student_attendance ENABLE ROW LEVEL SECURITY;
-- No policies: service role only.

-- ----------------------------------------------------------------------------
-- 4. student_roster_members — the leader's own curated list
--
-- Never pushed to CCB. A leader adding or removing someone here changes only
-- their private list; CCB group membership is read-only to this toolkit.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS student_roster_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_leader_id BIGINT NOT NULL REFERENCES student_leaders(id) ON DELETE CASCADE,
  ccb_individual_id TEXT NOT NULL,
  term TEXT NOT NULL,
  added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  removed_at TIMESTAMPTZ,
  -- Server-side, unlike the circle toolkit's localStorage snooze: student
  -- leaders switch phones, and a snooze that evaporates is worse than none.
  snoozed_until TIMESTAMPTZ,
  -- What the absence was when snoozed, so the snooze self-voids the moment the
  -- student shows up again (same rule as the circle toolkit's client version).
  snoozed_on_last_attended DATE
);

CREATE UNIQUE INDEX IF NOT EXISTS student_roster_members_unique_idx
  ON student_roster_members (student_leader_id, ccb_individual_id, term);

CREATE INDEX IF NOT EXISTS student_roster_members_active_idx
  ON student_roster_members (student_leader_id, term)
  WHERE removed_at IS NULL;

ALTER TABLE student_roster_members ENABLE ROW LEVEL SECURITY;
-- No policies: service role only.

-- ----------------------------------------------------------------------------
-- 5. Push — ports of the circle toolkit's three notification tables, FK'd to
--    student_leaders. The Teams Toolkit has no push at all, so there is no
--    lighter template to copy from.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS student_push_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_leader_id BIGINT NOT NULL REFERENCES student_leaders(id) ON DELETE CASCADE,
  endpoint TEXT NOT NULL UNIQUE,
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  user_agent TEXT,
  device_label TEXT,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  last_successful_delivery_at TIMESTAMPTZ,
  last_failed_delivery_at TIMESTAMPTZ,
  failure_count INTEGER NOT NULL DEFAULT 0,
  disabled_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS student_push_subscriptions_leader_idx
  ON student_push_subscriptions (student_leader_id, enabled);

ALTER TABLE student_push_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS student_notification_preferences (
  student_leader_id BIGINT PRIMARY KEY REFERENCES student_leaders(id) ON DELETE CASCADE,
  inbox_push_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  roster_absence_push_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  badge_count_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  push_nudge_requested_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE student_notification_preferences ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS student_notification_deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_type TEXT NOT NULL CHECK (notification_type IN ('inbox_message', 'roster_absence')),
  student_leader_id BIGINT NOT NULL REFERENCES student_leaders(id) ON DELETE CASCADE,
  push_subscription_id BIGINT REFERENCES student_push_subscriptions(id) ON DELETE SET NULL,
  inbox_recipient_id BIGINT,
  message_id UUID,
  delivery_status TEXT NOT NULL,
  error_message TEXT,
  sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- One push per recipient row — the guard that stops a retry double-notifying.
CREATE UNIQUE INDEX IF NOT EXISTS student_notification_deliveries_inbox_idx
  ON student_notification_deliveries (inbox_recipient_id)
  WHERE notification_type = 'inbox_message' AND inbox_recipient_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS student_notification_deliveries_leader_idx
  ON student_notification_deliveries (student_leader_id, sent_at DESC);

ALTER TABLE student_notification_deliveries ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------------------------------
-- 6. student_inbox_recipients — read receipts against the SHARED inbox message
--    table. Messages live in circle_summary_inbox_messages under the new
--    'student' audience so staff compose in the screens they already know;
--    only the recipient join is student-specific, because
--    circle_summary_inbox_recipients.leader_id FKs to circle_leaders.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS student_inbox_recipients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id UUID NOT NULL REFERENCES circle_summary_inbox_messages(id) ON DELETE CASCADE,
  student_leader_id BIGINT NOT NULL REFERENCES student_leaders(id) ON DELETE CASCADE,
  read_at TIMESTAMPTZ,
  read_version INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS student_inbox_recipients_unique_idx
  ON student_inbox_recipients (message_id, student_leader_id);

CREATE INDEX IF NOT EXISTS student_inbox_recipients_unread_idx
  ON student_inbox_recipients (student_leader_id)
  WHERE read_at IS NULL;

ALTER TABLE student_inbox_recipients ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------------------------------
-- 7. student_leaders — import identity + onboarding state
-- ----------------------------------------------------------------------------
ALTER TABLE student_leaders
  -- Lets /import-students re-run against the CCB student-leaders group without
  -- duplicating people.
  ADD COLUMN IF NOT EXISTS ccb_individual_id TEXT,
  ADD COLUMN IF NOT EXISTS source_ccb_group_id TEXT,
  ADD COLUMN IF NOT EXISTS term TEXT,
  -- Student leaders are frequently minors themselves (a high-school junior
  -- leading middle-schoolers). The shipped table carries `phone` and an index
  -- on it but no birthday, so lib/messaging/minorGuard.ts had nothing to
  -- evaluate and any future staff "text this leader" affordance would sail
  -- straight through the age gate. getGroupParticipants returns birthday
  -- inline, so filling this costs nothing at import.
  ADD COLUMN IF NOT EXISTS birthday TEXT,
  -- Mirrors the circle toolkit's onboarding state (which also lives on the
  -- leader row rather than a side table).
  ADD COLUMN IF NOT EXISTS toolkit_home_screen_completed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS toolkit_home_screen_dismissed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS toolkit_notifications_completed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS toolkit_notifications_dismissed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS toolkit_roster_completed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS toolkit_roster_dismissed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS toolkit_onboarding_completed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;

CREATE UNIQUE INDEX IF NOT EXISTS student_leaders_ccb_individual_idx
  ON student_leaders (ccb_individual_id)
  WHERE ccb_individual_id IS NOT NULL;

-- ----------------------------------------------------------------------------
-- 8. Widen the toolkit `audience` discriminator to admit 'student'
--
-- 20260622000000_toolkit_audience_and_team_targeting.sql added these as inline
-- unnamed CHECKs inside ADD COLUMN, so Postgres generated the names. Look them
-- up rather than guessing, then re-add under explicit names so the next widening
-- is a one-liner. Existing 'circle'/'host_team' rows are untouched.
-- ----------------------------------------------------------------------------
DO $$
DECLARE
  target TEXT;
  con_name TEXT;
  targets TEXT[] := ARRAY[
    'circle_summary_messages',
    'circle_summary_inbox_messages',
    'circle_leader_resources',
    'circle_leader_resource_pages',
    'leader_pro_tips'
  ];
BEGIN
  FOREACH target IN ARRAY targets LOOP
    IF to_regclass('public.' || target) IS NULL THEN
      CONTINUE;
    END IF;

    FOR con_name IN
      SELECT con.conname
      FROM pg_constraint con
      JOIN pg_class rel ON rel.oid = con.conrelid
      JOIN pg_namespace ns ON ns.oid = rel.relnamespace
      WHERE ns.nspname = 'public'
        AND rel.relname = target
        AND con.contype = 'c'
        AND pg_get_constraintdef(con.oid) ILIKE '%audience%'
    LOOP
      EXECUTE format('ALTER TABLE public.%I DROP CONSTRAINT %I', target, con_name);
    END LOOP;

    EXECUTE format(
      'ALTER TABLE public.%I ADD CONSTRAINT %I CHECK (audience IN (''circle'', ''host_team'', ''student''))',
      target, target || '_audience_check'
    );
  END LOOP;
END $$;

-- ----------------------------------------------------------------------------
-- 9. Retire student_messages
--
-- Created by 20260622000000_student_toolkit.sql and never read or written by any
-- application code. Student announcements now live in circle_summary_messages
-- under the 'student' audience, so staff use the Message Center they already
-- know instead of a fourth composer.
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS student_messages;

-- ----------------------------------------------------------------------------
-- 10. Tighten student_leaders RLS
--
-- 20260622000000_student_toolkit.sql granted SELECT to every authenticated
-- Supabase user. Student leaders are frequently minors and every read path is a
-- server route running on the service role, so drop the browser policy and
-- match the no-policy pattern used by student_sessions and the rest of the
-- tables above.
-- ----------------------------------------------------------------------------
DROP POLICY IF EXISTS "Authenticated read student_leaders" ON student_leaders;
